<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MuzammilLaptop" failures="3" tests="4" name="Command line test" time="3.413" errors="0" timestamp="2023-02-05T15:57:12 IST">
  <testcase classname="basic_cal.addition" name="setup" time="1.491"/>
  <testcase classname="basic_cal.addition" name="addition_TC_01" time="0.631">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	result is not matching expected [15] but found [15.00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
result is not matching expected [15] but found [15.00]
at basic_cal.addition.addition_TC_01(addition.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at basic_cal.test_run.main(test_run.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addition_TC_01 -->
  <testcase classname="basic_cal.addition" name="addition_TC_02" time="0.462">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Result is not matching expected [3] but found [3.00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Result is not matching expected [3] but found [3.00]
at basic_cal.addition.addition_TC_02(addition.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at basic_cal.test_run.main(test_run.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addition_TC_02 -->
  <testcase classname="basic_cal.addition" name="addition_TC_03" time="0.47">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Result is not matching expected [-7] but found [-7.00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Result is not matching expected [-7] but found [-7.00]
at basic_cal.addition.addition_TC_03(addition.java:105)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at basic_cal.test_run.main(test_run.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addition_TC_03 -->
</testsuite> <!-- Command line test -->
